### ISSUE TITLE
Add evolution data to details pokemon page

### ISSUE THREAD

**Issue by igihcksn** [igihcksn/mypocketmonsters#3]

**Comment by tchestnut85** [comment]
Hi @igihcksn , I'd like to give this a shot. Can you assign it to me?

**Comment by igihcksn** [comment]
Yes sure @tchestnut85 let me know if u have done with this issue, don't forget to attach the screenshot, thank you

**Comment by tchestnut85** [comment]
@igihcksn Thanks! Going to work on it today.

**Comment by tchestnut85** [comment]
Opened PR #24 for this. If you'd like more data/details added, please let me know. Thank you.
