### ISSUE TITLE
Improve header section

### ISSUE THREAD

**Issue by igihcksn** [igihcksn/mypocketmonsters#6]
This issue require to improve the header to get better

**Comment by panchoroo** [comment]
I'm interested in this, can you please give more details about what you would like to change?

**Comment by panchoroo** [comment]
Do you mean replacing the current hero banner with a new one that has a title, description and a new photo? Or adding something else on top of that current hero that's more like a nav bar?

**Comment by igihcksn** [comment]
Hi @panchoroo i put a comment on ur [PR](https://github.com/igihcksn/mypocketmonsters/pull/16), kindly help to check
