### ISSUE TITLE
Add navigation menu below search form 

### ISSUE THREAD

**Issue by igihcksn** [igihcksn/mypocketmonsters#8]

**Comment by khush021** [comment]
Can I take this?

**Comment by igihcksn** [comment]
> Can I take this?

Sure @khush021, let me know after ur change is done, and don't forget to add the screenshot please, thank you

**Comment by igihcksn** [comment]
Maybe can add like a Region, Items, Generation, and My Pokemon (do it for the desktop first), for mobile we can discuss after this one, for the styling feel free to improve
